name: platypus-binder
channels:
- conda-forge
dependencies:
- python==3.10.*
- pip
- git
- cython
- numpy
- matplotlib-base
- qutip
- sympy
- pylatexenc
- numexpr
- pip:
  - pandas
  - ipywidgets>=8.0,<8.2
  - qiskit[visualization]==1.0.1
  - qiskit-ibm-runtime==0.20.0
  - qiskit-ibm-provider==0.9.0
  - qiskit-aer==0.13.3
  - qiskit-algorithms==0.3.0
  - bokeh==3.0.2
  - seaborn==0.13.2
  - prototype-zne==1.3.1
  - git+https://github.com/qiskit-community/Quantum-Challenge-Grader.git@main
  - quadratic_programs
  - circuit-knitting-toolbox
