name: platypus-binder
channels:
- conda-forge
dependencies:
- python==3.8.*
- pip==20.*
- git>=2.35.0
- cython
- numpy
- matplotlib-base
- qutip
- sympy
- pylatexenc
- numexpr
- pip:
  - pandas
  - torchvision
  - ipywidgets>=7.3.0,<8.0
  - qiskit==0.45.0
  - qiskit-ibm-runtime==0.15.0
  - qiskit-nature==0.6.0
  - qiskit-machine-learning==0.4.0
  - qiskit-finance==0.3.2
  - qiskit-machine-learning[sparse]
  - qiskit-experiments==0.4.0
  - tweedledum==1.1.1
  - ./qiskit-textbook-src
  - 'qiskit-machine-learning[sparse]'
  # - ibm_quantum_widgets
  - tensorflow==2.9.3
  - pyscf==2.0.1
  - galois~=0.3
  - bokeh==3.0.2
  - seaborn==0.12.1
  - git+https://github.com/qiskit-community/Quantum-Challenge-Grader.git@main
  - git+https://github.com/anedumla/quantum_linear_solvers
  - git+https://github.com/NCCR-SPIN/topological_codes.git
