name: platypus-binder
channels:
- conda-forge
dependencies:
- python==3.8.*
- pip==20.*
- git>=2.35.0
- cython
- numpy
- matplotlib-base
- qutip
- sympy
- pylatexenc
- numexpr
- pip:
  - pandas
  - qiskit[all]~=0.37.0
  - ./qiskit-textbook-src
  - 'qiskit-machine-learning[sparse]'
  - ibm_quantum_widgets
  - tensorflow==2.9.1
  - pyscf==2.0.1
  - git+https://github.com/qiskit-community/Quantum-Challenge-Grader.git@main
