name: platypus-binder
channels:
- conda-forge
dependencies:
- python==3.8.*
- pip==20.*
- git>=2.35.0
- cython
- numpy
- matplotlib-base
- qutip
- sympy
- pylatexenc
- numexpr
- pip:
  - pandas
  - torchvision
  - qiskit[all]~=0.39.0
  - qiskit-ibm-runtime~=0.7.0
  - ./qiskit-textbook-src
  - 'qiskit-machine-learning[sparse]'
  - ibm_quantum_widgets
  - tensorflow==2.9.3
  - pyscf==2.0.1
  - bokeh==3.0.2
  - git+https://github.com/qiskit-community/Quantum-Challenge-Grader.git@main
  - git+https://github.com/anedumla/quantum_linear_solvers
  - git+https://github.com/NCCR-SPIN/topological_codes.git
