name: platypus-binder
channels:
- conda-forge
dependencies:
- python==3.8.*
- pip==20.*
- git>=2.35.0
- cython
- numpy
- matplotlib-base
- qutip
- sympy
- pylatexenc
- numexpr
- pip:
  - pandas
  - qiskit
  - ./qiskit-textbook-src
  - qiskit-machine-learning
  - 'qiskit-machine-learning[sparse]'
  - tensorflow
  - ibm_quantum_widgets
  - git+https://github.com/qiskit-community/Quantum-Challenge-Grader.git@777a406
